export default function Home(){
const nav=['⌂  Domov','♧  Obvestila  2','☵  Klepet pavšalistov','●  Zemljevid kampa','♟  Pavšalisti','▣  Dogodki','⚠  Prijavi težavo','☁  Vreme & morje','▤  Mali oglasi','◉  Kam danes?','▧  Galerija','ⓘ  Vse informacije','♥  SOS / Kontakti','🤖  JOŽE AI'];
const notices=[['💧','Prekinitev vode v coni B','10. jul 2025, 08:15'],['⚡','Dela na električnem omrežju','9. jul 2025, 19:42'],['ⓘ','Piknik pavšalistov','8. jul 2025, 12:30']];
const events=[['12 JUL','Turnir v balinanju','Sobota, 17:00'],['15 JUL','Večerno druženje','Torek, 20:00'],['20 JUL','Otroške igre','Nedelja, 10:00']];
return <main className="shell"><aside><div className="brand"><b>☀️🌲🌊</b><h1>VELI JOŽE</h1><small>KAMP SAVUDRIJA</small><p>Naš kamp. Naša skupnost. Naše poletje.</p></div><nav>{nav.map((n,i)=><div className={i===0?'active':''} key={n}>{n}</div>)}</nav></aside>
<section className="content"><header><input placeholder="⌕  Išči po portalu..."/><span>🔔 <i>2</i>　✉️　👨🏻 <b>Jure123</b>⌄</span></header>
<div className="hero"><div className="shade"><small>NEURADNI PORTAL SKUPNOSTI PAVŠALISTOV KAMPA</small><h2>VELI JOŽE</h2><p>Naš kamp. Naša skupnost. Naše poletje.</p></div></div>
<div className="stats"><article>☀️ <b>24 °C</b><small>Savudrija<br/>Morje: 22 °C</small></article><article>👥 <b>84</b><small>pavšalistov online</small></article><article>🗓️ <b>3</b><small>dogodki ta teden</small></article><article>📣 <b>2</b><small>nova obvestila</small></article></div>
<div className="grid"><div className="panel"><h3>Zadnja obvestila <a>Vse obvestila →</a></h3>{notices.map(x=><div className="row" key={x[1]}><strong>{x[0]}</strong><p><b>{x[1]}</b><small>{x[2]}</small></p><em>›</em></div>)}</div>
<div className="panel"><h3>Prihajajoči dogodki <a>Vsi dogodki →</a></h3>{events.map(x=><div className="row" key={x[1]}><strong className="date">{x[0]}</strong><p><b>{x[1]}</b><small>{x[2]}</small></p><em>›</em></div>)}</div>
<div className="panel quick"><h3>Hitre povezave</h3>{['📍 Zemljevid kampa','💬 Klepet','🏪 Mali oglasi','🍴 Kam danes?','📷 Galerija','⚠️ Prijavi težavo'].map(x=><button key={x}>{x}</button>)}</div></div>
<div className="tiles"><article><b>Zemljevid kampa</b><small>Parcele, sanitarije, plaže, trgovina ...</small></article><article><b>Galerija Veli Jože</b><small>Vaše fotografije in spomini</small></article><article><b>Kam danes?</b><small>Restavracije, konobe, izleti ...</small></article><article><b>Vreme & morje</b><small>Napoved, veter, temperature ...</small></article></div>
<div className="bottom"><div className="rooms"><h3>💬 Klepet pavšalistov</h3>{['Splošno　46','Druženje　23','Pomoč　12','Kupim / prodam　19','Izgubljeno / najdeno　5'].map(x=><p key={x}>{x}</p>)}</div><div className="chat"><h3>👥 Splošno <small>46 online</small></h3><p><b>Jure123</b> Čudovit sončni zahod danes! 🌅</p><p><b>Nina</b> Se vidimo zvečer na plaži. Kdo še pride?</p><p><b>Marko</b> Mi pridemo! 😊</p><input placeholder="Napiši sporočilo..."/></div><div className="ai"><h3>🤖 JOŽE AI</h3><p>Tvoj pomočnik za vse informacije o kampu Veli Jože.</p>{['Kdaj je odprta recepcija?','Kakšno bo vreme jutri?','Kje je najbližji veterinar?','Kaj se dogaja ta vikend?'].map(x=><button key={x}>{x}</button>)}<input placeholder="Zapiši svoje vprašanje..."/></div></div>
<div className="mobilebar">⌂<span>💬</span><span>🏪</span><span>♙</span></div></section></main>}
