import Link from "next/link";
import Icon from "./Icon";
export default function Home(){
const nav=[['home','Domov','/'],['bell','Obvestila','/obvestila'],['chat','Klepet pavšalistov','/klepet'],['map','Zemljevid kampa','/zemljevid'],['users','Pavšalisti','/pavsalisti'],['calendar','Dogodki','/dogodki'],['alert','Prijavi težavo','/tezave'],['cloud','Vreme & morje','/vreme'],['market','Mali oglasi','/oglasi'],['pin','Kam danes?','/kam-danes'],['image','Galerija','/galerija'],['info','Vse informacije','/informacije'],['heart','SOS / Kontakti','/sos'],['bot','JOŽE AI','/joze-ai']];
const notices=[['💧','Prekinitev vode v coni B','10. jul 2025, 08:15'],['⚡','Dela na električnem omrežju','9. jul 2025, 19:42'],['ⓘ','Piknik pavšalistov','8. jul 2025, 12:30']];
const events=[['12 JUL','Turnir v balinanju','Sobota, 17:00'],['15 JUL','Večerno druženje','Torek, 20:00'],['20 JUL','Otroške igre','Nedelja, 10:00']];
return <main className="shell"><aside><div className="brand"><div className="brandMark" aria-hidden="true"><span className="brandSun"/><span className="brandHill"/><span className="brandSea"/></div><h1>VELI JOŽE</h1><small>KAMP SAVUDRIJA</small><p>Naš kamp. Naša skupnost. Naše poletje.</p></div><nav>{nav.map((n,i)=><Link className={i===0?'active':''} key={n[2]} href={n[2]}><Icon name={n[0]}/><span>{n[1]}</span>{n[1]==='Obvestila'&&<em>2</em>}</Link>)}</nav></aside>
<section className="content"><header><div className="searchBox"><Icon name="search"/><input aria-label="Išči po portalu" placeholder="Išči po portalu ..."/></div><div className="topActions"><Link className="notificationLink" aria-label="Obvestila" href="/obvestila"><Icon name="bell"/><i>2</i></Link><Link className="topProfile" href="/profil"><span className="topAvatar">J</span><span><b>Jure123</b><small>Pavšalist</small></span></Link></div></header>
<div className="hero"><div className="shade"><small>NEURADNI PORTAL SKUPNOSTI PAVŠALISTOV KAMPA</small><h2>VELI JOŽE</h2><p>Naš kamp. Naša skupnost. Naše poletje.</p></div></div>
<div className="demoRibbon">DEMO PODATKI · do priklopa produkcijskih virov</div><div className="stats"><article>☀️ <b>24 °C</b><small>Savudrija<br/>Morje: 22 °C</small></article><article>👥 <b>84</b><small>pavšalistov online</small></article><article>🗓️ <b>3</b><small>dogodki ta teden</small></article><article>📣 <b>2</b><small>nova obvestila</small></article></div>
<div className="grid"><div className="panel"><h3>Zadnja obvestila <Link href="/obvestila">Vse obvestila →</Link></h3>{notices.map(x=><div className="row" key={x[1]}><strong>{x[0]}</strong><p><b>{x[1]}</b><small>{x[2]}</small></p><em>›</em></div>)}</div>
<div className="panel"><h3>Prihajajoči dogodki <Link href="/dogodki">Vsi dogodki →</Link></h3>{events.map(x=><div className="row" key={x[1]}><strong className="date">{x[0]}</strong><p><b>{x[1]}</b><small>{x[2]}</small></p><em>›</em></div>)}</div>
<div className="panel quick"><h3>Hitre povezave</h3>{[['📍 Zemljevid kampa','/zemljevid'],['💬 Klepet','/klepet'],['🏪 Mali oglasi','/oglasi'],['🍴 Kam danes?','/kam-danes'],['📷 Galerija','/galerija'],['⚠️ Prijavi težavo','/tezave']].map(x=><Link className="quickBtn" key={x[1]} href={x[1]}>{x[0]}</Link>)}</div></div>
<div className="tiles"><Link href="/zemljevid"><b>Zemljevid kampa</b><small>Parcele, sanitarije, plaže, trgovina ...</small></Link><Link href="/galerija"><b>Galerija Veli Jože</b><small>Vaše fotografije in spomini</small></Link><Link href="/kam-danes"><b>Kam danes?</b><small>Restavracije, konobe, izleti ...</small></Link><Link href="/vreme"><b>Vreme & morje</b><small>Napoved, veter, temperature ...</small></Link></div>
<div className="bottom"><div className="rooms"><h3>💬 Klepet pavšalistov</h3>{['Splošno　46','Druženje　23','Pomoč　12','Kupim / prodam　19','Izgubljeno / najdeno　5'].map(x=><p key={x}>{x}</p>)}</div><div className="chat"><h3>👥 Splošno <small>46 online</small></h3><p><b>Jure123</b> Čudovit sončni zahod danes! 🌅</p><p><b>Nina</b> Se vidimo zvečer na plaži. Kdo še pride?</p><p><b>Marko</b> Mi pridemo! 😊</p><input placeholder="Napiši sporočilo..."/></div><div className="ai"><h3>🤖 JOŽE AI</h3><p>Tvoj pomočnik za vse informacije o kampu Veli Jože.</p>{['Kdaj je odprta recepcija?','Kakšno bo vreme jutri?','Kje je najbližji veterinar?','Kaj se dogaja ta vikend?'].map(x=><Link className="aiQuickLink" key={x} href="/joze-ai">{x}</Link>)}<Link className="aiAskLink" href="/joze-ai">Vprašaj JOŽE AI ...</Link></div></div>
<div className="mobilebar"><Link href="/"><Icon name="home"/><small>Domov</small></Link><Link href="/klepet"><Icon name="chat"/><small>Klepet</small></Link><Link className="mobileMain" href="/tezave"><Icon name="alert"/><small>Prijavi</small></Link><Link href="/oglasi"><Icon name="market"/><small>Oglasi</small></Link><Link href="/profil"><Icon name="users"/><small>Profil</small></Link></div></section></main>}
