"use client";
import {FormEvent,useState} from "react";
import Link from "next/link";
export default function Page(){
 const [msg,setMsg]=useState("");const [busy,setBusy]=useState(false);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setMsg("");const f=new FormData(e.currentTarget);const password=String(f.get("password")||"");if(password.length<8){setMsg("Geslo naj vsebuje najmanj 8 znakov.");return}setBusy(true);const r=await fetch("/api/register",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(Object.fromEntries(f))});const d=await r.json();setMsg(d.message||"Registracije trenutno ni mogoče zaključiti.");setBusy(false)}
 return <main className="module"><Link href="/" className="back">← Domov</Link><div className="authExperience">
 <section className="authWelcome"><span>POSTANI DEL SKUPNOSTI</span><h2>Naš kamp. Naši ljudje.</h2><p>Profil pavšalista ti odpre skupnostne funkcije portala, zasebni podatki pa ostanejo zaščiteni.</p><div className="authBenefits"><small>✓ Profil pavšalista</small><small>✓ Klepet in pomoč</small><small>✓ Mali oglasi</small><small>✓ Dogodki in obvestila</small></div></section>
 <section className="authPane"><h3>Registracija pavšalista</h3><p>Po registraciji bo profil pred uporabo skupnostnih funkcij potrjen.</p><form className="functionalForm" onSubmit={submit}><input name="name" required autoComplete="name" placeholder="Ime in priimek"/><input name="nickname" required placeholder="Vzdevek"/><input name="email" required type="email" autoComplete="email" placeholder="E-pošta"/><select name="zone" required defaultValue=""><option value="" disabled>Izberi cono</option><option>A</option><option>B</option><option>C</option><option>D</option></select><input name="parcel" required placeholder="Številka parcele"/><input name="password" required type="password" autoComplete="new-password" minLength={8} placeholder="Geslo (najmanj 8 znakov)"/><div className="authPrivacy"><span>🔒</span><span>E-pošta in številka parcele nista javna podatka. Cono bo mogoče skriti v nastavitvah profila.</span></div><label className="consentRow"><input name="consent" type="checkbox" required/><span>Strinjam se s pravili skupnosti in obdelavo podatkov za namen delovanja profila pavšalista.</span></label><button disabled={busy}>{busy?"Pošiljam ...":"Pošlji registracijo"}</button>{msg&&<p className="formMessage">{msg}</p>}<p className="authSwitch">Že imaš profil? <Link href="/prijava">Prijava</Link></p></form></section>
 </div></main>;
}
